### ISSUE TITLE
invalid MAC

### ISSUE THREAD

**Issue by hannesm** [hannesm/ocaml-otr#4]
is sometimes reported... maybe if A sends M1 while M2 (from B) is in transit? -- add some debug hooks and hunt this bug down - it is annoying!

**Comment by hannesm** [comment]
unfortunately still don't have a reliable way to reproduce -- any hints are welcome

**Comment by hannesm** [comment]
can't reproduce anymore...

**Comment by cfcs** [comment]
I just got this again, with a build from january 28: https://github.com/cfcs/jackline/tree/build_jan28
ocaml-otr from opam: upstream-checksum: 158e88118ca758175159bac2201511d8
jackline upstream: https://github.com/cfcs/jackline/commit/46cd33bf895b8320ebbe747930e784651e965b7b

when talking to Python OTR (upstream from git) with Gajim

**Comment by hannesm** [comment]
yeah... if you've a debug trace or a realiable way to reproduce that'd be great... happened to me at some point - but I believe it is jackline and not otr's fault... need some time to get proper tracing framework for otr and debug it, though...

**Comment by hannesm** [comment]
finally debugged and fixed in https://github.com/mirleft/ocaml-nocrypto/commit/6b749387588e87bcee02842f0f4a704a8978f9b0
